matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 2.7
      services:
        - docker
      env:
        - DOCKER_OS=ubuntu16.04
    - os: linux
      dist: trusty
      sudo: required
      language: python  
      python: 3.5
      services:
        - docker
      env:
        - DOCKER_OS=ubuntu16.04
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 2.7
      services:
        - docker
      env:
        - DOCKER_OS=centos7
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.5
      services:
        - docker
      env:
        - DOCKER_OS=centos7
    - os: osx
      osx_image: xcode7.2
      language: generic
      python: 2.7
      env:
        - PYTHON_VERSION=2.7  # Workaround since TRAVIS_PYTHON_VERSION isn't being picked up
    - os: osx
      osx_image: xcode7.2
      language: generic
      python: 3.5
      env:
        - PYTHON_VERSION=3.5  # Workaround since TRAVIS_PYTHON_VERSION isn't being picked up

before_install:
  # Show work directory
  - pwd

install:
  # Linux, Docker
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker build -f Dockerfile-$DOCKER_OS-py${TRAVIS_PYTHON_VERSION} -t fredrikaverpil/pyside2-$DOCKER_OS-py${TRAVIS_PYTHON_VERSION} . ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run --rm -v $(pwd):/pyside-setup/dist fredrikaverpil/pyside2-$DOCKER_OS-py${TRAVIS_PYTHON_VERSION} ; fi
  # Mac OS X
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then chmod +x build_osx_py${PYTHON_VERSION}.sh ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./build_osx_py${PYTHON_VERSION}.sh ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then mv ~/pyside-setup/dist/*.whl . ; fi

before_script:
  - pwd  # Show work directory

script:
  - ls -al *.whl  # Show generated wheel
  # - pip install *.whl  # To do: Test portability of wheel
