language: python

sudo: required
dist: trusty

python:
  - 2.7
  - 3.5

services:
  - docker

install:
  - docker build -f Dockerfile-Ubuntu16.04-py${TRAVIS_PYTHON_VERSION} -t fredrikaverpil/pyside2-ubuntu16.04-py2.7 .

script:
  - docker run --rm -v $(pwd):/pyside-setup/dist fredrikaverpil/pyside2-ubuntu16.04-py2.7
