build: false

# Notes
# VCVARSALL: https://msdn.microsoft.com/en-us/library/f2ccy3wt.aspx#Anchor_1

environment:
  # Global variables
  CMAKE: "C:\\Program Files (x86)\\cmake\\bin\\cmake.exe"
  
  matrix:

    # Qt 5.6, Python 2.7 32-bit, MSVC2015 (v14)
    - PYTHON: "C:\\Python27"
      QT: "C:\\Qt\\5.6\\msvc2015"
      OPENSSL: "C:\\OpenSSL-Win32\\bin"
      VCVARSALL: "\"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\" x86"
      os: Visual Studio 2015
      platform: x86
      fast_finish: true

    # Qt 5.6, Python 2.7 64-bit, MSVC2015 (v14)
    - PYTHON: "C:\\Python27-x64"
      QT: "C:\\Qt\\5.6\\msvc2015_64"
      OPENSSL: "C:\\OpenSSL-Win64\\bin"
      VCVARSALL: "\"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\" amd64"
      os: Visual Studio 2015
      platform: x64
      fast_finish: true

    # # Qt 5.6, Python 3.5 32-bit, MSVC2015 (v14)
    # - PYTHON: "C:\\Python35"
    #   QT: "C:\\Qt\\5.6\\msvc2015"
    #   OPENSSL: "C:\\OpenSSL-Win32\\bin"
    # VCVARSALL: '"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" x86'
    #   os: Visual Studio 2015
    #   platform: x86
    #   fast_finish: true

    # # Qt 5.6, Python 3.5 64-bit, MSVC2015 (v14)
    # - PYTHON: "C:\\Python35-x64"
    #   QT: "C:\\Qt\\5.6\\msvc2015_64"
    #   OPENSSL: "C:\\OpenSSL-Win64\\bin"
    #   VCVARSALL: '"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" amd64'
    #   os: Visual Studio 2015
    #   platform: x64
    #   fast_finish: true

    # # Qt 5.7, Python 2.7 32-bit, MSVC2015 (v14)
    # - PYTHON: "C:\\Python27"
    #   QT: "C:\\Qt\\5.7\\msvc2015"
    #   OPENSSL: "C:\\OpenSSL-Win32\\bin"
    # VCVARSALL: '"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" x86'
    #   os: Visual Studio 2015
    #   platform: x86
    #   fast_finish: true

    # # Qt 5.7, Python 2.7 64-bit, MSVC2015 (v14)
    # - PYTHON: "C:\\Python27-x64"
    #   QT: "C:\\Qt\\5.7\\msvc2015_64"
    #   OPENSSL: "C:\\OpenSSL-Win64\\bin"
    #   VCVARSALL: '"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" amd64'
    #   os: Visual Studio 2015
    #   platform: x64
    #   fast_finish: true

    # # Qt 5.7, Python 3.5 32-bit, MSVC2015 (v14)
    # - PYTHON: "C:\\Python35"
    #   QT: "C:\\Qt\\5.7\\msvc2015"
    #   OPENSSL: "C:\\OpenSSL-Win32\\bin"
    # VCVARSALL: '"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" x86'
    #   os: Visual Studio 2015
    #   platform: x86
    #   fast_finish: true

    # # Qt 5.7, Python 3.5 64-bit, MSVC2015 (v14)
    # - PYTHON: "C:\\Python35-x64"
    #   QT: "C:\\Qt\\5.7\\msvc2015_64"
    #   OPENSSL: "C:\\OpenSSL-Win64\\bin"
    #   VCVARSALL: '"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" amd64'
    #   os: Visual Studio 2015
    #   platform: x64
    #   fast_finish: true


init:
  - "ECHO %PYTHON%"
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - git clone --recursive https://codereview.qt-project.org/pyside/pyside-setup C:\pyside-setup
  - call "%VCVARSALL%"

install:
  - pip install wheel
  - python C:\pyside-setup\setup.py bdist_wheel --ignore-git --qmake="%QT%\bin\qmake.exe" --openssl="%OPENSSL" --cmake="%CMAKE%"

test_script:
  - dir C:\pyside-setup\dist\*.whl
