build: false

environment:
  GLOBALVAR: something
  matrix:
    - PYTHON: "C:\\Python35-x64"
      os: Visual Studio 2015
      platform: x64
      fast_finish: true

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - git clone --recursive https://codereview.qt-project.org/pyside/pyside-setup C:\pyside-setup
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

install:
  - pip install wheel
  - python C:\pyside-setup\setup.py bdist_wheel --ignore-git --qmake="C:\Qt\5.6\msvc2015_64\bin\qmake.exe" --openssl="C:\OpenSSL-Win64\bin" --cmake="C:\Program Files (x86)\cmake\bin\cmake.exe"

test_script:
  - dir